### PR TITLE
Behavior documentation

### PR DESCRIPTION
**Pull request by dotpointer**
This pull request adds documentation to the behaviors.

Please have a look to see if it conforms with the expectations. Want 2 approves on this.

### CODE REVIEW

**Comment by dotpointer** [comment]
It is for some reason not possible to assign Neovici/frontend here.

**Comment by cristinecula** [comment]
@dotpointer Is this PR still relevant? I would like to rebase and merge this branch.

**Comment by cristinecula** [comment]
@dotpointer @nomego rebased this branch and submitted as separate PR (because I cannot push to this repo) https://github.com/Neovici/cosmoz-behaviors/pull/28

**Comment by nomego** [comment]
Closing in favor of #28

**Pull request closed without merging**
